# Generated by Django 4.2.30 on 2026-08-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="commission_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="commission_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="currency",
            field=models.CharField(default="YER", max_length=3, verbose_name="العملة"),
        ),
        migrations.AddField(
            model_name="order",
            name="dispute_reason",
            field=models.TextField(blank=True, verbose_name="سبب النزاع"),
        ),
        migrations.AddField(
            model_name="order",
            name="provider_net_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "في الانتظار"),
                    ("processing", "قيد المعالجة"),
                    ("paid", "مدفوع"),
                    ("failed", "فشل"),
                    ("refunded", "مسترد"),
                    ("cancelled", "ملغي"),
                ],
                default="pending",
                max_length=20,
                verbose_name="حالة الدفع",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "في انتظار الموافقة"),
                    ("accepted", "مقبول"),
                    ("payment_pending", "بانتظار الدفع"),
                    ("paid", "مدفوع"),
                    ("in_progress", "قيد التنفيذ"),
                    ("delivered", "تم التسليم"),
                    ("completed", "مكتمل"),
                    ("rejected", "مرفوض"),
                    ("cancelled", "ملغي"),
                    ("disputed", "متنازع عليه"),
                ],
                default="pending",
                max_length=20,
                verbose_name="حالة الطلب",
            ),
        ),
    ]
