# Generated by Django 4.2.30 on 2026-08-20 15:53

import apps.accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_delete_pendingproviderprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.accounts.models.provider_document_path
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد المراجعة"),
                            ("approved", "مقبول"),
                            ("rejected", "مرفوض"),
                            ("needs_additional_documents", "يحتاج مستندات إضافية"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=40,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "مستند مقدم خدمة",
                "verbose_name_plural": "مستندات مقدمي الخدمات",
                "permissions": [
                    ("review_provider_document", "Can review provider document"),
                    ("verify_provider", "Can verify provider"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProviderDocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("is_required", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "نوع مستند مقدم الخدمة",
                "verbose_name_plural": "أنواع مستندات مقدمي الخدمات",
            },
        ),
        migrations.AddField(
            model_name="providerprofile",
            name="admin_notes",
            field=models.TextField(blank=True, verbose_name="ملاحظات الإدارة"),
        ),
        migrations.AddField(
            model_name="providerprofile",
            name="availability",
            field=models.CharField(blank=True, max_length=120, verbose_name="التوفر"),
        ),
        migrations.AddField(
            model_name="providerprofile",
            name="business_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="اسم العمل"
            ),
        ),
        migrations.AddField(
            model_name="providerprofile",
            name="city",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, verbose_name="المدينة"
            ),
        ),
        migrations.AddField(
            model_name="providerprofile",
            name="display_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="اسم العرض"
            ),
        ),
        migrations.AddField(
            model_name="providerprofile",
            name="district",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, verbose_name="المنطقة"
            ),
        ),
        migrations.AddField(
            model_name="providerprofile",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="بريد العمل"
            ),
        ),
        migrations.AddField(
            model_name="providerprofile",
            name="experience",
            field=models.TextField(blank=True, verbose_name="الخبرات"),
        ),
        migrations.AddField(
            model_name="providerprofile",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="هاتف العمل"
            ),
        ),
        migrations.AddField(
            model_name="providerprofile",
            name="qualifications",
            field=models.TextField(blank=True, verbose_name="المؤهلات"),
        ),
        migrations.AddField(
            model_name="providerprofile",
            name="service_radius",
            field=models.PositiveIntegerField(
                default=10, verbose_name="نطاق الخدمة بالكيلومتر"
            ),
        ),
        migrations.AddField(
            model_name="providerprofile",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("unverified", "غير موثق"),
                    ("pending_review", "قيد المراجعة"),
                    ("verified", "موثق"),
                    ("rejected", "مرفوض"),
                    ("needs_documents", "يحتاج مستندات"),
                    ("suspended", "موقوف"),
                ],
                db_index=True,
                default="unverified",
                max_length=30,
                verbose_name="حالة التوثيق",
            ),
        ),
        migrations.AddField(
            model_name="providerprofile",
            name="verified_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="وقت التوثيق"
            ),
        ),
        migrations.AddField(
            model_name="providerprofile",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_provider_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="providerprofile",
            name="experience_years",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="سنوات الخبرة"
            ),
        ),
        migrations.AlterField(
            model_name="providerprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "قيد المراجعة"),
                    ("active", "نشط"),
                    ("inactive", "غير نشط"),
                    ("suspended", "موقوف"),
                ],
                db_index=True,
                default="inactive",
                max_length=20,
                verbose_name="حالة الحساب",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "عميل"),
                    ("provider", "مقدم خدمة"),
                    ("admin", "مدير"),
                    ("super_admin", "مدير عام"),
                ],
                default="customer",
                max_length=20,
                verbose_name="الدور",
            ),
        ),
        migrations.AddIndex(
            model_name="providerprofile",
            index=models.Index(
                fields=["verification_status", "city"],
                name="accounts_pr_verific_6808a8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="providerprofile",
            index=models.Index(
                fields=["status", "is_available"], name="accounts_pr_status_da77a4_idx"
            ),
        ),
        migrations.AddField(
            model_name="providerdocument",
            name="document_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="accounts.providerdocumenttype",
            ),
        ),
        migrations.AddField(
            model_name="providerdocument",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="accounts.providerprofile",
            ),
        ),
        migrations.AddField(
            model_name="providerdocument",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_provider_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="providerdocument",
            index=models.Index(
                fields=["provider", "status"], name="accounts_pr_provide_07eea9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="providerdocument",
            index=models.Index(
                fields=["document_type", "status"],
                name="accounts_pr_documen_22b599_idx",
            ),
        ),
    ]
