# Generated by Django 4.2.30 on 2026-08-20 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_providerdocument_providerdocumenttype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="providerprofile",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-90),
                    django.core.validators.MaxValueValidator(90),
                ],
                verbose_name="خط العرض",
            ),
        ),
        migrations.AlterField(
            model_name="providerprofile",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                ],
                verbose_name="خط الطول",
            ),
        ),
    ]
