# Generated by Django 4.2.30 on 2026-08-20 16:42

import apps.accounts.models
import apps.accounts.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_providerprofile_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="providerdocument",
            name="file",
            field=models.FileField(
                storage=apps.accounts.storage.PrivateMediaStorage(),
                upload_to=apps.accounts.models.provider_document_path,
            ),
        ),
    ]
