# Generated by Django 4.2.30 on 2026-08-20 15:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_providerdocument_providerdocumenttype_and_more"),
        ("marketplace", "0006_delete_pendingservice"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "price_type",
                    models.CharField(
                        choices=[
                            ("fixed", "سعر ثابت"),
                            ("hourly", "بالساعة"),
                            ("negotiable", "قابل للتفاوض"),
                        ],
                        default="fixed",
                        max_length=20,
                    ),
                ),
                (
                    "estimated_duration",
                    models.PositiveIntegerField(default=1, help_text="Days"),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "خدمة مقدم الخدمة",
                "verbose_name_plural": "خدمات مقدمي الخدمات",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="categories/",
                verbose_name="صورة التصنيف",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True,
                max_length=120,
                null=True,
                unique=True,
                verbose_name="الرابط المختصر",
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["is_active", "order"], name="marketplace_is_acti_82ee6f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["slug"], name="marketplace_slug_d22abd_idx"),
        ),
        migrations.AddConstraint(
            model_name="service",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("price__gte", 0), ("price__isnull", True), _connector="OR"
                ),
                name="service_price_non_negative",
            ),
        ),
        migrations.AddField(
            model_name="providerservice",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="provider_services",
                to="accounts.providerprofile",
            ),
        ),
        migrations.AddField(
            model_name="providerservice",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="provider_services",
                to="marketplace.service",
            ),
        ),
        migrations.AddIndex(
            model_name="providerservice",
            index=models.Index(
                fields=["service", "is_active"], name="marketplace_service_893bff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="providerservice",
            index=models.Index(
                fields=["provider", "is_active"], name="marketplace_provide_66d8d4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="providerservice",
            unique_together={("provider", "service")},
        ),
    ]
